### ISSUE TITLE
AttributeError: Can't pickle local object '_ion_type_for.<locals>.IonPyValueType'

### ISSUE THREAD

**Issue by yosoufe** [amzn/ion-python#126]
Hello, 
I need to use multiprocessing module of python and I would like to pass `IonPy*` types between processes but it seems those objects are not picklable. 

In order to reproduce, the following code
```py
from amazon.ion import simpleion as ion
import multiprocessing

def process_main(return_queue):
    return_queue.put(ion.IonPyText("test text"))
    print("DO Something")

if __name__== "__main__":
    ctx = multiprocessing.get_context('spawn')
    return_queue = ctx.Queue()
    p = ctx.Process(target = process_main, args=(return_queue,))
    p.start()
    p.join(10)
    p.terminate()
```
is creating the following output message:
```
DO Something
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 241, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object '_ion_type_for.<locals>.IonPyValueType'
```

It can be because the `IonPyValueType` class is being defined [inside a function](https://github.com/amzn/ion-python/blob/master/amazon/ion/simple_types.py#L136) rather than in top level of the module and accoding to [python documentation](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled) that would make it unpicklable.

I would be grateful of any feedback? Am I doing something wrong?  Is there any workaround that I am missing?
Thanks

**Comment by yosoufe** [comment]
[This change](https://github.com/yosoufe/ion-python/commit/bfdabeb38fc89d98e10d5df6278f49e450b8ff44) seems to solve the above problem but I have another problem that I want to reproduce it. 

With the above change,
I have IonPy* attribute for a custom objects and during the unpickling I get the following error
```
TypeError: __new__() missing 1 required positional argument: 'value'
```

**Comment by yosoufe** [comment]
Ok I think I resolved the bug above as well in [this commit](https://github.com/yosoufe/ion-python/commit/69f2fbaa346a92f1d289d914aa09f0681aa25d20). `Enum` classed needed `__getnewargs__` function definition. I would run the tests and if it was ok I will open a PR. Let me know if you see something wrong here. Thanks

**Comment by yosoufe** [comment]
Closing. Resolved by the merged PR above.
