### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'ion_type'

### ISSUE THREAD

**Issue by jamesdbowman** [amzn/ion-python#85]
### Issue

Upon using the `simpleion.dump` method to encode a `tuple` in Ion binary, I encountered the following error:

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/amazon/ion/simpleion.py", line 184, in _dump
    ion_type = obj.ion_type
AttributeError: 'tuple' object has no attribute 'ion_type'
```

The string representation of the dict I am attempting to encode:

```
{'TupleKey': ('a', 'tuple')}
```

### Expected Behavior

The [docs for `simpleion.dump`](https://github.com/amzn/ion-python/blob/master/amazon/ion/simpleion.py#L93) list a possible `tuple` -> Ion list conversion, I expected to receive an Ion list as part of the encoded bytes.

**Comment by tgregg** [comment]
Here's the full trace that I was able to reproduce:

```
Traceback (most recent call last):
  File "/Users/greggt/Documents/workspace/ion-python/amazon/ion/simpleion.py", line 184, in _dump
    ion_type = obj.ion_type
AttributeError: 'tuple' object has no attribute 'ion_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/greggt/Documents/workspace/ion-python/amazon/ion/simpleion.py", line 259, in dumps
    ignore_nan=ignore_nan, int_as_string_bitcount=int_as_string_bitcount, iterable_as_array=iterable_as_array)
  File "/Users/greggt/Documents/workspace/ion-python/amazon/ion/simpleion.py", line 146, in dump
    _dump(obj, writer)
  File "/Users/greggt/Documents/workspace/ion-python/amazon/ion/simpleion.py", line 197, in _dump
    _dump(val, writer, field)
  File "/Users/greggt/Documents/workspace/ion-python/amazon/ion/simpleion.py", line 187, in _dump
    ion_type = _ion_type(obj)
  File "/Users/greggt/Documents/workspace/ion-python/amazon/ion/simpleion.py", line 178, in _ion_type
    raise TypeError('Unknown scalar type %r' % (type(obj),))
TypeError: Unknown scalar type <class 'tuple'>
```
It looks like tuple isn't registered in the [_FROM_TYPE](https://github.com/amzn/ion-python/blob/master/amazon/ion/simpleion.py#L149) lookup table. It should map to `LIST`.
